import { expandGlob } from "std/fs";
import { join } from "std/path";

const RULES_DIR = "src/data/rules";
const OUTPUT_FILE = "src/data/cipai-list.ts";

async function main() {
  const imports: string[] = [];
  const exportItems: string[] = [];

  console.log(`Scanning ${RULES_DIR} for JSON rules...`);

  let count = 0;
  for await (const file of expandGlob(join(RULES_DIR, "*.json"))) {
    const filename = file.name;
    const varName = filename.replace(/[^a-zA-Z0-9]/g, "_").replace(
      /^([0-9])/,
      "_$1",
    );
    const importPath = `./rules/${filename}`;

    imports.push(
      `import ${varName} from '${importPath}' with { type: "json" };`,
    );
    exportItems.push(`${varName} as unknown as Cipai`);
    count++;
  }

  let content = "import { Cipai } from '../logic/prosody-engine.ts';\n";

  for (const imp of imports) {
    content += imp + "\n";
  }

  content += "\n// This file is auto-generated by update_rules.ts.\n";
  content +=
    "// Do not edit manually. Add new JSON rules to src/data/rules/ instead.\n\n";
  content += "export const CIPAI_LIST: Cipai[] = [\n";
  content += "  " + exportItems.join(",\n  ") + "\n";
  content += "];\n";

  await Deno.writeTextFile(OUTPUT_FILE, content);
  console.log(`Successfully updated ${OUTPUT_FILE} with ${count} rules.`);
}

if (import.meta.main) {
  main();
}
