import { Cipai } from '../logic/prosody-engine.ts';
import die_lian_hua_json from './rules/die_lian_hua.json' with { type: "json" };
import nian_nu_jiao_json from './rules/nian_nu_jiao.json' with { type: "json" };
import pu_sa_man_json from './rules/pu_sa_man.json' with { type: "json" };
import ru_meng_ling_json from './rules/ru_meng_ling.json' with { type: "json" };
import yi_qin_e_json from './rules/yi_qin_e.json' with { type: "json" };
import yu_mei_ren_json from './rules/yu_mei_ren.json' with { type: "json" };

// This file is auto-generated by update_rules.ts.
// Do not edit manually. Add new JSON rules to src/data/rules/ instead.

export const CIPAI_LIST: Cipai[] = [
  die_lian_hua_json as unknown as Cipai,
  nian_nu_jiao_json as unknown as Cipai,
  pu_sa_man_json as unknown as Cipai,
  ru_meng_ling_json as unknown as Cipai,
  yi_qin_e_json as unknown as Cipai,
  yu_mei_ren_json as unknown as Cipai
];
